name: ticketing-dev

services:
  mysql:
    image: mysql:8.4
    container_name: ticketing-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: ticketing-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redpanda:
    image: redpandadata/redpanda:v24.1.11
    container_name: ticketing-redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"

  backend:
    image: gradle:8.10.2-jdk17
    container_name: ticketing-backend
    restart: "no"
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - gradle_cache:/home/gradle/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: local
      TICKETING_QUEUE_ENABLED: "false"
      SPRING_KAFKA_CONSUMER_GROUP_ID: ticketing-confirm-local-20260217
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: latest
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ticketing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
    command: ["bash", "-lc", "chmod +x gradlew && ./gradlew --no-daemon bootRun --stacktrace"]
    depends_on:
      - mysql
      - redis
      - redpanda
    ports:
      - "8080:8080"

  frontend:
    image: node:20-alpine
    container_name: ticketing-frontend
    restart: unless-stopped
    working_dir: /workspace
    volumes:
      - ./frontend/ticketing-ui:/workspace
      - ticketing-frontend-node_modules:/workspace/node_modules
    ports:
      - "5173:5173"
    command: sh -lc "if [ -f package-lock.json ]; then npm ci; else npm install; fi && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
  gradle_cache:
  ticketing-frontend-node_modules:
