ticketing:
  queue:
    advance-interval-ms: 200

spring:
  kafka:
    consumer:
      group-id: ticketing-confirm-local-20260217
      auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings,prometheus"
