global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ticketing-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]  # bootRun(로컬) 기준
